# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PBlog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PBlog
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'PBlogTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PBlogUITests' do
    # Pods for testing
  end

end
